---
- name: Just the facts, ma'am...
  hosts: haproxy
  remote_user: root
  gather_facts: true

  tasks:
    - name: Get LXD Config User variables
      ansible.builtin.script:
        cmd: get_config.sh
      register: lxd_config_user
      when: ansible_virtualization_type == 'lxc'

    - name: Set Facts
      ansible.builtin.set_fact:
        lxd_user_var: "{{ lxd_config_user.stdout }}"
        cacheable: true
      when: ansible_virtualization_type == 'lxc'

    - name: Install HAProxy on HAProxy containers
      ansible.builtin.include_role:
        name: app_haproxy
      when: (lxd_user_var.app is defined) and (lxd_user_var.app | lower == 'haproxy') | default('UNDEFINED')
